=== Dathard/2024-se_school/core/Schema/cli-commands.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="commands">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="command" type="commandDeclaration" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="commandDeclaration">
        <xs:sequence>
            <xs:element name="params" type="paramsDeclaration" minOccurs="0" maxOccurs="1" />
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required" />
        <xs:attribute name="class" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name="paramsDeclaration">
        <xs:sequence>
            <xs:element name="param" type="paramDeclaration" minOccurs="1" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="paramDeclaration">
        <xs:attribute name="name" type="xs:string" use="required" />
        <xs:attribute name="required" type="xs:boolean" use="required" />
        <xs:attribute name="description" type="xs:string" use="required" />
    </xs:complexType>
</xs:schema>

=== Dathard/2024-se_school/core/cli-commands.xml
<?xml version="1.0"?>
<commands xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Schema/cli-commands.xsd">
    <command name="install" class="Core\Cli\InstallCommand">
        <params>
            <param name="db-host" required="true" description="The database server’s fully qualified hostname or IP address."/>
            <param name="db-name" required="true" description="Name of the database instance in which you want to install the database tables."/>
            <param name="db-user" required="true" description="Username of the database instance owner."/>
            <param name="db-password" required="true" description="Database instance owner’s password."/>
        </params>
    </command>
    <command name="send-email-notifications" class="App\Cli\SendEmailNotificationsCommand"/>
</commands>
